## Required Packages check

In [1]:
import pandas as pd
import numpy as np

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.15.0


In [4]:
import os

In [5]:
import matplotlib as plt

In [6]:
import seaborn as sns

In [7]:
from sklearn import datasets

In [8]:
import sklearn

In [9]:
from sklearn.preprocessing import MinMaxScaler

## TensorFlow Check

In [10]:
hello = tf.constant("Hello World!")

In [11]:
sess = tf.Session()

In [12]:
print(sess.run(hello))

b'Hello World!'


In [13]:
tf.Session

tensorflow.python.client.session.Session

In [14]:
np.random.randint(1,100,4)

array([81, 24, 21, 92])

In [15]:
data = np.random.randint(1,100,(10,2))
print(data)

[[79 22]
 [35 25]
 [ 3 53]
 [45 34]
 [50 31]
 [36 69]
 [54 71]
 [29 17]
 [43 28]
 [70 15]]


In [16]:
scaler = MinMaxScaler()

In [17]:
scaler.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [18]:
type(scaler)

sklearn.preprocessing.data.MinMaxScaler

In [19]:
scaler.transform(data)

array([[1.        , 0.125     ],
       [0.42105263, 0.17857143],
       [0.        , 0.67857143],
       [0.55263158, 0.33928571],
       [0.61842105, 0.28571429],
       [0.43421053, 0.96428571],
       [0.67105263, 1.        ],
       [0.34210526, 0.03571429],
       [0.52631579, 0.23214286],
       [0.88157895, 0.        ]])

In [20]:
pd_df = pd.DataFrame(data = np.random.randint(1,101,(50,10)))

In [21]:
pd_df.head()

0   1   2   3   4   5   6   7   8   9
0  52  18  13  77  41  36  49  33  80  60
1  66  11  63  86  62  91  83  62  94  55
2  77   7  60  50  64  96  43  73  93  10
3  55  70  64   4  76  58  27  29  52   6
4  75  17  45  87  61  64  67  56  90  51

In [22]:
y = pd_df[9]
y.head()

0    60
1    55
2    10
3     6
4    51
Name: 9, dtype: int32

In [23]:
x = pd_df.drop(columns = [9])
x.head()

0   1   2   3   4   5   6   7   8
0  52  18  13  77  41  36  49  33  80
1  66  11  63  86  62  91  83  62  94
2  77   7  60  50  64  96  43  73  93
3  55  70  64   4  76  58  27  29  52
4  75  17  45  87  61  64  67  56  90

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [26]:
X_train.shape

(33, 9)

#### All the packages are imported!